"""List and Tasks statuses

Revision ID: 51572944bcec
Revises: 83b8f71d6025
Create Date: 2019-07-01 15:29:08.756523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51572944bcec'
down_revision = '83b8f71d6025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('del_status', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('done_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'done_status')
    op.drop_column('list', 'del_status')
    # ### end Alembic commands ###
